version: 2.1

# defaults: &defaults
#     machine:
#       image: ubuntu-2004:202101-01
#       docker_layer_caching: true
#     resource_class: arm.medium

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Running build"
          command: make build
      - run:
          name: "Print architecture info"
          command: uname -a
      - persist_to_workspace:
          root: .
          paths:
            - bin/*
            - lib/*
  
  arm-test:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Building tests"
          command: make -C test/testContainers all

workflows:
  version: 2
  arm-workflow:
    jobs:
      - arm-build:
          filters:
             branches:
               only: circleci-project-setup
      - arm-test:
          requires:
          - arm-build
          filters:
             branches:
               only: circleci-project-setup