version: 2.1

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Running build"
          command: make build
      - run:
          name: "Building tests"
          command: make -C test/testContainers all
      - run:
          name: "Print architecture info"
          command: uname -a

workflows:
  arm-workflow:
    jobs:
      - arm-build
